# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_duration', models.TextField()),
                ('time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('start_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exp', models.CharField(blank=True, default=None, max_length=10)),
                ('salary', models.IntegerField()),
                ('time', models.TimeField()),
                ('course', models.ManyToManyField(to='app1.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=15)),
                ('mobile', models.CharField(blank=True, default=None, max_length=15)),
                ('batch', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='app1.Course')),
            ],
        ),
    ]
