# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_course_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='time',
        ),
    ]
