# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_staff_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
